using System;
class TestApp {
  public static void Main( void ) {
   int i;

   try {
    i = i +1;

}
   catch {
    Console.WriteLine("Exception caught.");
   }
  }
}
